=== dhein1030/security-automation-content-repository/content-model/src/main/xsd/MetaModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  The MIT License
  
  Copyright (c) 2011 David Waltermire
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://scapdev.org/schema/meta-model/0.1"
  xmlns:tns="http://scapdev.org/schema/meta-model/0.1"
  targetNamespace="http://scapdev.org/schema/meta-model/0.1" elementFormDefault="qualified"
  attributeFormDefault="unqualified" version="0.1">

  <xs:element name="meta-model">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="external-identifiers" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="external-identifier" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="schemas">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="schema" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:key name="SchemaKey">
      <xs:selector xpath=".//tns:schema"/>
      <xs:field xpath="@id"/>
    </xs:key>

    <xs:key name="EntityKey">
      <xs:selector xpath=".//tns:schema/tns:entities/tns:entity"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="EntityKeyRef" refer="EntityKey">
      <xs:selector xpath=".//tns:entity-ref"/>
      <xs:field xpath="@id-ref"/>
    </xs:keyref>

    <xs:key name="KeyKey">
      <xs:selector xpath=".//tns:schema/tns:entities/tns:entity/tns:key"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="KeyKeyRef" refer="KeyKey">
      <xs:selector xpath=".//tns:key-ref"/>
      <xs:field xpath="@id-ref"/>
    </xs:keyref>

    <xs:key name="FieldKey">
      <xs:selector xpath=".//tns:field"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="FieldKeyRef" refer="FieldKey">
      <xs:selector xpath=".//tns:field-ref"/>
      <xs:field xpath="@id-ref"/>
    </xs:keyref>
    <!-- TODO: write a schematron that enforces key/key-ref field/field-ref -->

    <xs:key name="RelationshipKey">
      <xs:selector xpath=".//tns:schema/tns:relationships/tns:relationship"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:unique name="KeyRefUnique">
      <xs:selector xpath=".//tns:key-ref"/>
      <xs:field xpath="@id"/>
    </xs:unique>
    <xs:unique name="FieldRefUnique">
      <xs:selector xpath=".//tns:field-ref"/>
      <xs:field xpath="@id"/>
    </xs:unique>

    <xs:key name="DocumentKey">
      <xs:selector xpath=".//tns:schema/tns:documents/tns:document"/>
      <xs:field xpath="@id"/>
    </xs:key>
    
    <xs:key name="ExternalIdentifierKey">
      <xs:selector xpath=".//tns:external-identifier"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="ExternalIdentifierKeyRef" refer="ExternalIdentifierKey">
      <xs:selector xpath=".//tns:external-identifier-ref"/>
      <xs:field xpath="@id-ref"/>
    </xs:keyref>
  </xs:element>

  <xs:complexType name="ComponentType">
    <xs:attribute name="id" type="ComponentIdType" use="required"/>
  </xs:complexType>

  <xs:complexType name="SchemaComponentType">
    <xs:complexContent>
      <xs:extension base="ComponentType">
        <xs:sequence>
          <xs:element ref="schema-node"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="ComponentIdType">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="urn:scap-content:[a-z-]+:[a-z][a-z0-9.-_]+:[a-z][a-z0-9.\-_]+"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- ********************************************************************** -->
  <!-- * External Identifier                                                             * -->
  <!-- ********************************************************************** -->
  <xs:simpleType name="ExternalIdentifierComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:external-identifier:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ExternalIdentifierType">
    <xs:attribute name="id" type="ExternalIdentifierComponentIdType" use="required"/>
  </xs:complexType>
  <xs:element name="external-identifier" type="ExternalIdentifierType"/>
  
  <!-- ********************************************************************** -->
  <!-- * Schema                                                             * -->
  <!-- ********************************************************************** -->
  <xs:simpleType name="SchemaComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:schema:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="SchemaSchemaComponentType">
    <xs:complexContent>
      <xs:restriction base="SchemaComponentType">
        <xs:sequence>
          <xs:element ref="schema-node"/>
        </xs:sequence>
        <xs:attribute name="id" type="SchemaComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="schema" type="SchemaType"/>
  <xs:complexType name="SchemaType">
    <xs:complexContent>
      <xs:extension base="SchemaSchemaComponentType">
        <xs:sequence>
          <xs:element name="entities" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="entity" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="relationships" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="relationship" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="documents" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element ref="document" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="namespace" type="xs:anyURI" use="required"/>
        <xs:attribute name="schemaLocation" type="xs:anyURI" use="required"/>
        <xs:attribute name="prefix" type="xs:NCName"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- ********************************************************************** -->
  <!-- * Entity                                                             * -->
  <!-- ********************************************************************** -->
  <xs:simpleType name="EntityComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:entity:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="EntitySchemaComponentType">
    <xs:complexContent>
      <xs:restriction base="SchemaComponentType">
        <xs:sequence>
          <xs:element ref="schema-node"/>
        </xs:sequence>
        <xs:attribute name="id" type="EntityComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="entity" type="EntityType"/>
  <xs:complexType name="EntityType">
    <xs:complexContent>
      <xs:extension base="EntitySchemaComponentType">
        <xs:sequence>
          <xs:element ref="key"/>
        </xs:sequence>
        <xs:attribute name="local-part" type="xs:NCName"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- ********************************************************************** -->
  <!-- * Document Entity                                                    * -->
  <!-- ********************************************************************** -->
  <xs:simpleType name="DocumentComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:document:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="DocumentSchemaComponentType">
    <xs:complexContent>
      <xs:restriction base="SchemaComponentType">
        <xs:sequence>
          <xs:element ref="schema-node"/>
        </xs:sequence>
        <xs:attribute name="id" type="DocumentComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="document" type="DocumentType"/>
  <xs:complexType name="DocumentType">
    <xs:complexContent>
      <xs:extension base="DocumentSchemaComponentType">
        <xs:sequence>
          <xs:element ref="document-model"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="SchemaReferenceType">
    <xs:attribute name="node" use="required"/>
    <xs:attribute name="javaLocation" default="TYPE">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="TYPE"/>
          <xs:enumeration value="FIELD"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:element name="schema-node" type="SchemaReferenceType"/>

  <xs:element name="entity-ref" type="EntityIdRefType"/>
  <xs:complexType name="EntityIdRefType">
    <xs:attribute name="id-ref" type="ComponentIdType"/>
  </xs:complexType>

  <!-- Keys -->
  <xs:simpleType name="KeyComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:key:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="KeyComponentType">
    <xs:complexContent>
      <xs:restriction base="ComponentType">
        <xs:attribute name="id" type="KeyComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="key" type="KeyType"/>
  <xs:complexType name="KeyType">
    <xs:complexContent>
      <xs:extension base="KeyComponentType">
        <xs:sequence>
          <xs:element name="field" type="FieldType" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Key Fields -->
  <xs:simpleType name="FieldComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:field:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="FieldSchemaComponentType">
    <xs:complexContent>
      <xs:restriction base="SchemaComponentType">
        <xs:sequence>
          <xs:element ref="schema-node"/>
        </xs:sequence>
        <xs:attribute name="id" type="FieldComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="FieldType">
    <xs:complexContent>
      <xs:extension base="FieldSchemaComponentType"> </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Document models -->
  <xs:element name="document-model" type="DocumentModelType" abstract="true"/>
  <xs:complexType name="DocumentModelType"/>

  <xs:element name="generated-document-model" type="GeneratedDocumentModelType"
    substitutionGroup="document-model"/>
  <xs:complexType name="GeneratedDocumentModelType">
    <xs:complexContent>
      <xs:extension base="DocumentModelType">
        <xs:sequence>
          <xs:element name="entity-container" type="EntityContainerType" maxOccurs="unbounded"/>
          <xs:element ref="generated-property" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="ContainerComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:container:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ContainerSchemaComponentType">
    <xs:complexContent>
      <xs:restriction base="SchemaComponentType">
        <xs:sequence>
          <xs:element ref="schema-node"/>
        </xs:sequence>
        <xs:attribute name="id" type="ContainerComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="EntityContainerType">
    <xs:complexContent>
      <xs:extension base="ContainerSchemaComponentType">
        <xs:sequence>
          <xs:element ref="entity-schema-node"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="EntityNodeReferenceType">
    <xs:complexContent>
      <xs:extension base="SchemaReferenceType">
        <xs:sequence>
          <xs:element ref="entity-ref" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="entity-schema-node" type="EntityNodeReferenceType"/>

  <xs:complexType name="GeneratedPropertyType">
    <xs:sequence>
      <xs:element ref="schema-node"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="generated-property" type="GeneratedPropertyType"/>

  <!-- ********************************************************************** -->
  <!-- * Relationship                                                       * -->
  <!-- ********************************************************************** -->
  <xs:simpleType name="RelationshipComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:relationship:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="RelationshipType" abstract="true">
    <xs:complexContent>
      <xs:restriction base="SchemaComponentType">
        <xs:sequence>
          <xs:element ref="schema-node"/>
        </xs:sequence>
        <xs:attribute name="id" type="RelationshipComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="relationship" type="RelationshipType" abstract="true"/>

  <!-- Key Refs -->
  <xs:simpleType name="KeyRefComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:key-ref:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="KeyRefComponentType">
    <xs:complexContent>
      <xs:restriction base="ComponentType">
        <xs:attribute name="id" type="KeyRefComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="KeyRefType">
    <xs:complexContent>
      <xs:extension base="KeyRefComponentType">
        <xs:sequence>
          <xs:element name="field-ref" type="FieldRefType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id-ref" type="KeyComponentIdType" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Key Fields -->
  <xs:simpleType name="FieldRefComponentIdType">
    <xs:restriction base="ComponentIdType">
      <xs:pattern value="urn:scap-content:field-ref:.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="FieldRefSchemaComponentType">
    <xs:complexContent>
      <xs:restriction base="SchemaComponentType">
        <xs:sequence>
          <xs:element ref="schema-node"/>
        </xs:sequence>
        <xs:attribute name="id" type="FieldRefComponentIdType" use="required"/>
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="FieldRefType">
    <xs:complexContent>
      <xs:extension base="FieldRefSchemaComponentType">
        <xs:attribute name="id-ref" type="FieldComponentIdType" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>


  <xs:complexType name="LocalRelationshipType">
    <xs:complexContent>
      <xs:extension base="RelationshipType">
        <xs:sequence>
          <xs:element name="key-ref" type="KeyRefType"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="local-relationship" type="LocalRelationshipType"
    substitutionGroup="relationship"/>

  <xs:complexType name="ExternalRelationshipType" abstract="true">
    <xs:complexContent>
      <xs:extension base="RelationshipType"> </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="external-relationship" type="ExternalRelationshipType"
    substitutionGroup="relationship"/>

  <!-- indirect relationship -->
  <xs:complexType name="ExternalIdentifierReferenceType">
    <!-- TODO: write a schematron rule requiring that qualifier-value is specified if qualifier is. -->
    <xs:attribute name="id-ref" type="ExternalIdentifierComponentIdType" use="required"/>
    <xs:attribute name="qualifier-value" type="xs:anyURI"/>
  </xs:complexType>
  
  <xs:complexType name="IndirectRelationshipType">
    <xs:complexContent>
      <xs:extension base="RelationshipType">
        <xs:sequence>
          <xs:element name="qualifier-node" type="SchemaReferenceType" minOccurs="0"/>
          <xs:element name="value-node" type="SchemaReferenceType"/>
          <xs:element name="external-identifier-ref" type="ExternalIdentifierReferenceType" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="indirect-relationship" type="IndirectRelationshipType"
    substitutionGroup="relationship"/>
</xs:schema>

=== dhein1030/security-automation-content-repository/content-meta-model/src/main/xml/oval-5.8-metamodel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  The MIT License
  
  Copyright (c) 2011 David Waltermire
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
-->
<meta-model xmlns="http://scapdev.org/schema/meta-model/0.1"
  xmlns:oval-def="http://oval.mitre.org/XMLSchema/oval-definitions-5"
  xmlns:nvd-vuln="http://scap.nist.gov/schema/feed/vulnerability/2.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://scapdev.org/schema/meta-model/0.1 ../../../../content-model/src/main/xsd/MetaModel.xsd">
  
  <external-identifiers>
    <external-identifier id="urn:scap-content:external-identifier:org.mitre:cve">
      <pattern>CVE-\d{4}-\d{4}</pattern>
    </external-identifier>
    <external-identifier id="urn:scap-content:external-identifier:org.mitre:cce-4">
      <pattern>CCE-\d+</pattern>
    </external-identifier>
    <external-identifier id="urn:scap-content:external-identifier:org.mitre:cce-5">
      <pattern>CCE-\d+-\d</pattern>
    </external-identifier>
    <external-identifier id="urn:scap-content:external-identifier:org.mitre:cwe">
      <pattern>CWE-\d+</pattern>
    </external-identifier>
    <external-identifier id="urn:scap-content:external-identifier:gov.nist:cpe-2-x">
      <pattern>[c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\._\-~%]*){0,6}</pattern>
    </external-identifier>
  </external-identifiers>

  <schemas>
    <!-- =================================================================== -->
    <!-- = OVAL 5.x                                                        = -->
    <!-- =================================================================== -->
    <schema id="urn:scap-content:schema:org.mitre:oval-definitions-5"
        namespace="http://oval.mitre.org/XMLSchema/oval-definitions-5"
        schemaLocation="../../../src/main/xsd/org/mitre/oval/XMLSchema/oval-definitions-schema.xsd"
        prefix="oval-def">
      <schema-node node="/xs:schema"/>
      
      <documents>
        <document id="urn:scap-content:document:org.mitre.oval:oval-document">
          <schema-node node="//xs:element[@name='oval_definitions']/xs:complexType"/>
          <generated-document-model>
            <entity-containers>
              <entity-container id="urn:scap-content:container:org.mitre.oval:definitions">
                <schema-node node="//xs:complexType[@name='DefinitionsType']/xs:sequence/xs:element[@ref='oval-def:definition']"/>
                <entity-ref id-ref="urn:scap-content:entity:org.mitre.oval:definition"/>
              </entity-container>
              <entity-container id="urn:scap-content:container:org.mitre.oval:tests">
                <schema-node node="//xs:complexType[@name='TestsType']/xs:sequence/xs:element[@ref='oval-def:test']"/>
                <entity-ref id-ref="urn:scap-content:entity:org.mitre.oval:test"/>
              </entity-container>
              <entity-container id="urn:scap-content:container:org.mitre.oval:objects">
                <schema-node node="//xs:complexType[@name='ObjectsType']/xs:sequence/xs:element[@ref='oval-def:object']"/>
                <entity-ref id-ref="urn:scap-content:entity:org.mitre.oval:object"/>
              </entity-container>
              <entity-container id="urn:scap-content:container:org.mitre.oval:states">
                <schema-node node="//xs:complexType[@name='StatesType']/xs:sequence/xs:element[@ref='oval-def:state']"/>
                <entity-ref id-ref="urn:scap-content:entity:org.mitre.oval:state"/>
              </entity-container>
              <entity-container id="urn:scap-content:container:org.mitre.oval:variables">
                <schema-node node="//xs:complexType[@name='VariablesType']/xs:sequence/xs:element[@ref='oval-def:variable']"/>
                <entity-ref id-ref="urn:scap-content:entity:org.mitre.oval:variable"/>
              </entity-container>
            </entity-containers>

            <generated-property-refs>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-generator"/>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-generator-schema-version">
                <value type="STATIC">5.8</value>
              </generated-property-ref>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-generator-timestamp">
                <value type="TIME">now</value>
              </generated-property-ref>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-generator-product-name">
                <value type="APP">product.cpe</value>
              </generated-property-ref>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-defintions"/>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-tests"/>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-objects"/>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-states"/>
              <generated-property-ref id-ref="urn:scap-content:generated:org.mitre.oval:oval-variables"/>
            </generated-property-refs>
          </generated-document-model>
        </document>
      </documents>
      
      <generated-properties>
        <generated-property id="urn:scap-content:generated:org.mitre.oval:oval-generator">
          <schema-node node="//xs:element[@name='oval_definitions']/xs:complexType/xs:sequence/xs:element[@name='generator']"/>
        </generated-property>
        <generated-property id="urn:scap-content:generated:org.mitre.oval:oval-defintions">
          <schema-node node="//xs:element[@name='oval_definitions']/xs:complexType/xs:sequence/xs:element[@name='definitions']"/>
        </generated-property>
        <generated-property id="urn:scap-content:generated:org.mitre.oval:oval-tests">
          <schema-node node="//xs:element[@name='oval_definitions']/xs:complexType/xs:sequence/xs:element[@name='tests']"/>
        </generated-property>
        <generated-property id="urn:scap-content:generated:org.mitre.oval:oval-objects">
          <schema-node node="//xs:element[@name='oval_definitions']/xs:complexType/xs:sequence/xs:element[@name='objects']"/>
        </generated-property>
        <generated-property id="urn:scap-content:generated:org.mitre.oval:oval-states">
          <schema-node node="//xs:element[@name='oval_definitions']/xs:complexType/xs:sequence/xs:element[@name='states']"/>
        </generated-property>
        <generated-property id="urn:scap-content:generated:org.mitre.oval:oval-variables">
          <schema-node node="//xs:element[@name='oval_definitions']/xs:complexType/xs:sequence/xs:element[@name='variables']"/>
        </generated-property>
      </generated-properties>

      <entities>
        <entity id="urn:scap-content:entity:org.mitre.oval:definition" local-part="definition">
          <schema-node node="//xs:complexType[@name='DefinitionType']"/>
          <key id="urn:scap-content:key:org.mitre.oval:definition">
            <field id="urn:scap-content:field:org.mitre.oval:definition">
              <schema-node node="xs:attribute[@name='id']"/>
            </field>
          </key>
          <identifier-mapping>
            <pattern-operation pattern="(oval:[A-Za-z0-9_\-\.]+:def:[1-9][0-9]*)">
              <field-value id-ref="urn:scap-content:field:org.mitre.oval:definition">$1</field-value>
            </pattern-operation>
          </identifier-mapping>
        </entity>
        <entity id="urn:scap-content:entity:org.mitre.oval:test">
          <schema-node node="//xs:complexType[@name='TestType']"/>
          <key id="urn:scap-content:key:org.mitre.oval:test">
            <field id="urn:scap-content:field:org.mitre.oval:test">
              <schema-node node="xs:attribute[@name='id']"/>
            </field>
          </key>
          <identifier-mapping>
            <pattern-operation pattern="(oval:[A-Za-z0-9_\-\.]+:tst:[1-9][0-9]*)">
              <field-value id-ref="urn:scap-content:field:org.mitre.oval:test">$1</field-value>
            </pattern-operation>
          </identifier-mapping>
        </entity>
        <entity id="urn:scap-content:entity:org.mitre.oval:object">
          <schema-node node="//xs:complexType[@name='ObjectType']"/>
          <key id="urn:scap-content:key:org.mitre.oval:object">
            <field id="urn:scap-content:field:org.mitre.oval:object">
              <schema-node node="xs:attribute[@name='id']"/>
            </field>
          </key>
          <identifier-mapping>
            <pattern-operation pattern="(oval:[A-Za-z0-9_\-\.]+:obj:[1-9][0-9]*)">
              <field-value id-ref="urn:scap-content:field:org.mitre.oval:object">$1</field-value>
            </pattern-operation>
